# Generated by Django 3.2.6 on 2024-06-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20240630_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateportfolio',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
