# Generated by Django 3.2.6 on 2024-06-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_templateportfolio_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateportfolio',
            name='unique_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='templateportfolio',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
